# This is a generated file. Not intended for manual editing.
services:
  cmoc:
    build:
      context: "/Users/dave/projects/cs/CMOC"
      dockerfile: "CMOC/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/CMOC.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/CMOC.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/Users/dave/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/Users/dave/.nuget/packages"
    image: "cmoc:dev"
    ports: []
    volumes:
    - "/Users/dave/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/Users/dave/projects/cs/CMOC/CMOC:/app:rw"
    - "/Users/dave/projects/cs/CMOC:/src:rw"
    working_dir: "/app"
