CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);

BEGIN TRANSACTION;

CREATE TABLE "Capability" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Capability" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL
);

CREATE TABLE "COMPONENT_TYPES" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_COMPONENT_TYPES" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL
);

CREATE TABLE "EQUIPMENT_REDUNDANCIES" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_EQUIPMENT_REDUNDANCIES" PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE "EQUIPMENT_TYPES" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_EQUIPMENT_TYPES" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL
);

CREATE TABLE "LOCATIONS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_LOCATIONS" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL
);

CREATE TABLE "ServiceRedundancy" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ServiceRedundancy" PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE "SERVICES" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SERVICES" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL
);

CREATE TABLE "EQUIPMENT" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_EQUIPMENT" PRIMARY KEY AUTOINCREMENT,
    "SerialNumber" TEXT NOT NULL,
    "TypeId" INTEGER NOT NULL,
    "LocationId" INTEGER NOT NULL,
    "Notes" TEXT NOT NULL,
    CONSTRAINT "FK_EQUIPMENT_EQUIPMENT_TYPES_TypeId" FOREIGN KEY ("TypeId") REFERENCES "EQUIPMENT_TYPES" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EQUIPMENT_LOCATIONS_LocationId" FOREIGN KEY ("LocationId") REFERENCES "LOCATIONS" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CAPABILITY_SUPPORT_RELATIONSHIPS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CAPABILITY_SUPPORT_RELATIONSHIPS" PRIMARY KEY AUTOINCREMENT,
    "ServiceId" INTEGER NOT NULL,
    "CapabilityId" INTEGER NOT NULL,
    "RedundantWithId" INTEGER NOT NULL,
    "ServiceRedundancyId" INTEGER NULL,
    CONSTRAINT "FK_CAPABILITY_SUPPORT_RELATIONSHIPS_Capability_CapabilityId" FOREIGN KEY ("CapabilityId") REFERENCES "Capability" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CAPABILITY_SUPPORT_RELATIONSHIPS_SERVICES_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "SERVICES" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CAPABILITY_SUPPORT_RELATIONSHIPS_ServiceRedundancy_RedundantWithId" FOREIGN KEY ("RedundantWithId") REFERENCES "ServiceRedundancy" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CAPABILITY_SUPPORT_RELATIONSHIPS_ServiceRedundancy_ServiceRedundancyId" FOREIGN KEY ("ServiceRedundancyId") REFERENCES "ServiceRedundancy" ("Id")
);

CREATE TABLE "SERVICE_SUPPORT_RELATIONSHIPS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SERVICE_SUPPORT_RELATIONSHIPS" PRIMARY KEY AUTOINCREMENT,
    "TypeId" INTEGER NOT NULL,
    "ServiceId" INTEGER NOT NULL,
    "FailureThreshold" INTEGER NOT NULL,
    "RedundantWithId" INTEGER NOT NULL,
    CONSTRAINT "FK_SERVICE_SUPPORT_RELATIONSHIPS_EQUIPMENT_REDUNDANCIES_RedundantWithId" FOREIGN KEY ("RedundantWithId") REFERENCES "EQUIPMENT_REDUNDANCIES" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SERVICE_SUPPORT_RELATIONSHIPS_EQUIPMENT_TYPES_TypeId" FOREIGN KEY ("TypeId") REFERENCES "EQUIPMENT_TYPES" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SERVICE_SUPPORT_RELATIONSHIPS_SERVICES_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "SERVICES" ("Id") ON DELETE CASCADE
);

CREATE TABLE "COMPONENT_RELATIONSHIPS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_COMPONENT_RELATIONSHIPS" PRIMARY KEY AUTOINCREMENT,
    "TypeId" INTEGER NOT NULL,
    "TypeId1" INTEGER NOT NULL,
    "EquipmentId" INTEGER NOT NULL,
    "FailureThreshold" INTEGER NOT NULL,
    CONSTRAINT "FK_COMPONENT_RELATIONSHIPS_COMPONENT_TYPES_TypeId" FOREIGN KEY ("TypeId") REFERENCES "COMPONENT_TYPES" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_COMPONENT_RELATIONSHIPS_COMPONENT_TYPES_TypeId1" FOREIGN KEY ("TypeId1") REFERENCES "COMPONENT_TYPES" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_COMPONENT_RELATIONSHIPS_EQUIPMENT_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "EQUIPMENT" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EquipmentServiceSupportRelationship" (
    "EquipmentId" INTEGER NOT NULL,
    "RelationshipsId" INTEGER NOT NULL,
    CONSTRAINT "PK_EquipmentServiceSupportRelationship" PRIMARY KEY ("EquipmentId", "RelationshipsId"),
    CONSTRAINT "FK_EquipmentServiceSupportRelationship_EQUIPMENT_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "EQUIPMENT" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EquipmentServiceSupportRelationship_SERVICE_SUPPORT_RELATIONSHIPS_RelationshipsId" FOREIGN KEY ("RelationshipsId") REFERENCES "SERVICE_SUPPORT_RELATIONSHIPS" ("Id") ON DELETE CASCADE
);

CREATE TABLE "COMPONENTS" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_COMPONENTS" PRIMARY KEY AUTOINCREMENT,
    "SerialNumber" TEXT NOT NULL,
    "ComponentTypeId" INTEGER NOT NULL,
    "TypeId" INTEGER NOT NULL,
    "Operational" INTEGER NOT NULL,
    "ComponentOfId" INTEGER NOT NULL,
    CONSTRAINT "FK_COMPONENTS_COMPONENT_RELATIONSHIPS_ComponentOfId" FOREIGN KEY ("ComponentOfId") REFERENCES "COMPONENT_RELATIONSHIPS" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_COMPONENTS_COMPONENT_TYPES_ComponentTypeId" FOREIGN KEY ("ComponentTypeId") REFERENCES "COMPONENT_TYPES" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_COMPONENTS_COMPONENT_TYPES_TypeId" FOREIGN KEY ("TypeId") REFERENCES "COMPONENT_TYPES" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CAPABILITY_SUPPORT_RELATIONSHIPS_CapabilityId" ON "CAPABILITY_SUPPORT_RELATIONSHIPS" ("CapabilityId");

CREATE INDEX "IX_CAPABILITY_SUPPORT_RELATIONSHIPS_RedundantWithId" ON "CAPABILITY_SUPPORT_RELATIONSHIPS" ("RedundantWithId");

CREATE INDEX "IX_CAPABILITY_SUPPORT_RELATIONSHIPS_ServiceId" ON "CAPABILITY_SUPPORT_RELATIONSHIPS" ("ServiceId");

CREATE INDEX "IX_CAPABILITY_SUPPORT_RELATIONSHIPS_ServiceRedundancyId" ON "CAPABILITY_SUPPORT_RELATIONSHIPS" ("ServiceRedundancyId");

CREATE INDEX "IX_COMPONENT_RELATIONSHIPS_EquipmentId" ON "COMPONENT_RELATIONSHIPS" ("EquipmentId");

CREATE INDEX "IX_COMPONENT_RELATIONSHIPS_TypeId" ON "COMPONENT_RELATIONSHIPS" ("TypeId");

CREATE INDEX "IX_COMPONENT_RELATIONSHIPS_TypeId1" ON "COMPONENT_RELATIONSHIPS" ("TypeId1");

CREATE INDEX "IX_COMPONENTS_ComponentOfId" ON "COMPONENTS" ("ComponentOfId");

CREATE INDEX "IX_COMPONENTS_ComponentTypeId" ON "COMPONENTS" ("ComponentTypeId");

CREATE INDEX "IX_COMPONENTS_TypeId" ON "COMPONENTS" ("TypeId");

CREATE INDEX "IX_EQUIPMENT_LocationId" ON "EQUIPMENT" ("LocationId");

CREATE INDEX "IX_EQUIPMENT_TypeId" ON "EQUIPMENT" ("TypeId");

CREATE INDEX "IX_EquipmentServiceSupportRelationship_RelationshipsId" ON "EquipmentServiceSupportRelationship" ("RelationshipsId");

CREATE INDEX "IX_SERVICE_SUPPORT_RELATIONSHIPS_RedundantWithId" ON "SERVICE_SUPPORT_RELATIONSHIPS" ("RedundantWithId");

CREATE INDEX "IX_SERVICE_SUPPORT_RELATIONSHIPS_ServiceId" ON "SERVICE_SUPPORT_RELATIONSHIPS" ("ServiceId");

CREATE INDEX "IX_SERVICE_SUPPORT_RELATIONSHIPS_TypeId" ON "SERVICE_SUPPORT_RELATIONSHIPS" ("TypeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230901005907_Initial', '7.0.10');

COMMIT;

